version: '3.8'
services:

  agent:
    image: datadog/agent:latest
    links:
      - mysql
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE:-datadoghq.com}
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

  app:
    build: app/
    links:
      - agent
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
      agent:
        condition: service_healthy
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=orders
      - APP_USER=orders
      - APP_PASSWORD=ordersPw
      - DD_SERVICE=orders-app
      - DD_ENV=development
      - DD_AGENT_HOST=agent

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 5s
      retries: 30
    volumes:
      - ./mysql/mysql.conf:/etc/mysql/conf.d/datadog.cnf
      - ./mysql/initdb/1_mysql-8_0.sql:/docker-entrypoint-initdb.d/1_mysql-8_0.sql
      - ./mysql/initdb/2_mysql-dbm-setup.sql:/docker-entrypoint-initdb.d/2_mysql-dbm-setup.sql
    labels:
      com.datadoghq.ad.check_names: '["mysql"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [{
          "dbm": true,
          "server": "%%host%%",
          "port": "3306",
          "user": "datadog",
          "pass": "dog",
          "query_samples": {"enabled": true},
          "query_metrics": {"enabled": true},
          "query_activity": {"enabled": true},
          "collect_schemas": {"enabled": true},
          "tags": ["env:development", "service:orders-app"]
        }]
