CREATE USER root WITH PASSWORD 'root';
ALTER USER root WITH SUPERUSER;
CREATE USER datadog WITH PASSWORD 'dog';
GRANT SELECT ON pg_stat_database TO datadog;

CREATE USER orders WITH PASSWORD 'ordersPw';
CREATE DATABASE orders;
GRANT ALL PRIVILEGES ON DATABASE orders TO orders;
GRANT CONNECT ON DATABASE orders TO datadog;
